/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Controlador.EmpleadoDAO;
import Controlador.TurnoDAO;
import Controlador.asistenciaDAO;
import Entidades.Asistencia;
import Entidades.Empleado;
import Entidades.Turno;
import java.sql.Time;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author NITRO
 */
public class frmEditAsistencia extends javax.swing.JFrame {

    Asistencia act;
    EmpleadoDAO emp=new EmpleadoDAO();
    TurnoDAO turn =new TurnoDAO();
    asistenciaDAO con=new  asistenciaDAO();
    /**
     * Creates new form frmEditAsistencia
     */
    public frmEditAsistencia(Asistencia ob) {
        initComponents();
        act=ob;
        emp.EmpleadosCombo(jComboBox1);
        turn.TurnoCombo(jComboBox2);
        cargarSpinner();
        cargarSpinner2();
         if (ob != null) {
           cargarDatos(ob);
        }
    }
    
    Asistencia crearObjeto(){
          Empleado empleadoSeleccionado = (Empleado) jComboBox1.getSelectedItem();
          int idEmpleado = empleadoSeleccionado.getIdEmpleado();
          
          Turno turnoSeleccionado = (Turno) jComboBox2.getSelectedItem();
          int idTurno = turnoSeleccionado.getIdTurno();
          
          Date fechaFin = (Date) jDateChooser1.getDate();
          String comentarios = jTextArea1.getText();
          
            Date dateEntrada = (Date) jSpinner1.getValue();
            Calendar calendarEntrada = Calendar.getInstance();
            calendarEntrada.setTime(dateEntrada);
            int horaInicio = calendarEntrada.get(Calendar.HOUR_OF_DAY);
            int minutoInicio = calendarEntrada.get(Calendar.MINUTE);
            Time horaInicioTime = new Time(horaInicio, minutoInicio, 0);

            // Obtén la hora de salida desde el JSpinner
            Date dateSalida = (Date) jSpinner2.getValue();
            Calendar calendarSalida = Calendar.getInstance();
            calendarSalida.setTime(dateSalida);
            int horaFin = calendarSalida.get(Calendar.HOUR_OF_DAY);
            int minutoFin = calendarSalida.get(Calendar.MINUTE);
            Time horaFinTime = new Time(horaFin, minutoFin, 0);
            
            String comentario=jTextArea1.getText();
            
            Asistencia obj=new Asistencia(0,idEmpleado,idTurno,fechaFin,horaInicioTime,horaFinTime,comentario);
            return obj;
    }
    
    public void cargarDatos(Asistencia obj) {
    // Configura el JTextField con el nombre del turno
    jTextArea1.setText(obj.getComentarios());

    int idEmpleado = obj.getIdEmpleado();
    Empleado empleado = emp.buscarEmpleado(idEmpleado);
     jComboBox1.setSelectedItem(empleado);
     
     int idTurno = obj.getIdTurno();
    Turno turno = turn.buscarTurno(idTurno);
     jComboBox2.setSelectedItem(turno);
    // Configura el JSpinner para la hora de entrada
    Time horaInicio = obj.getHoraEntrada();
    Calendar calendarInicio = Calendar.getInstance();
    calendarInicio.setTime(horaInicio);
    jSpinner1.setValue(calendarInicio.getTime());

    // Configura el JSpinner para la hora de salida
    Time horaFin = obj.getHoraSalida();
    Calendar calendarFin = Calendar.getInstance();
    calendarFin.setTime(horaFin);
    jSpinner2.setValue(calendarFin.getTime());
    jDateChooser1.setDate(obj.getFecha());
    
    }
    
     void cargarSpinner() {
    // Configura el modelo SpinnerDateModel con la hora actual
    SpinnerDateModel timeModel = new SpinnerDateModel(new Date(), null, null, Calendar.MINUTE);

    // Configura el editor del JSpinner para usar el formato de hora
    JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jSpinner1, "HH:mm");

    // Configura el JSpinner existente con el modelo y el editor
    jSpinner1.setModel(timeModel);
    jSpinner1.setEditor(timeEditor);
    }
   
    void cargarSpinner2( ) {
    // Configura el modelo SpinnerDateModel con la hora actual
    SpinnerDateModel timeModel2 = new SpinnerDateModel(new Date(), null, null, Calendar.MINUTE);

    // Configura el editor del JSpinner para usar el formato de hora
    JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(jSpinner2, "HH:mm");

    // Configura el JSpinner existente con el modelo y el editor
    jSpinner2.setModel(timeModel2);
    jSpinner2.setEditor(timeEditor2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione Empleado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Seleccione su turno");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Fecha de ingreso");

        jLabel4.setText("Comentarios");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Hora de entrada");

        jLabel6.setText("Hora salida");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));

        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));

        jButton1.setText("Cancelar");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(act==null){
            con.insertarAsistencia(crearObjeto());
        }else{
            Asistencia obj= crearObjeto();
            obj.setIdAsistencia(act.getIdAsistencia());
 
            con.modificarAsistencia(obj);
        }
        frmAsistencia.Listar();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
