/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Controlador.TurnoDAO;
 
import Entidades.Turno;
import java.sql.Time;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author NITRO
 */
public class frmEditTurno extends javax.swing.JFrame {

    Turno act = null;
    TurnoDAO con=new TurnoDAO();
    
    public frmEditTurno(Turno ob) {
        initComponents();
        act = ob;
          cargarSpinner();
           cargarSpinner2();
         if (ob != null) {
             cargarDatos(ob);
         } 
    }

   void cargarSpinner() {
    // Configura el modelo SpinnerDateModel con la hora actual
    SpinnerDateModel timeModel = new SpinnerDateModel(new Date(), null, null, Calendar.MINUTE);

    // Configura el editor del JSpinner para usar el formato de hora
    JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jSpinner1, "HH:mm");

    // Configura el JSpinner existente con el modelo y el editor
    jSpinner1.setModel(timeModel);
    jSpinner1.setEditor(timeEditor);
    }
   
    void cargarSpinner2( ) {
    // Configura el modelo SpinnerDateModel con la hora actual
    SpinnerDateModel timeModel2 = new SpinnerDateModel(new Date(), null, null, Calendar.MINUTE);

    // Configura el editor del JSpinner para usar el formato de hora
    JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(jSpinner2, "HH:mm");

    // Configura el JSpinner existente con el modelo y el editor
    jSpinner2.setModel(timeModel2);
    jSpinner2.setEditor(timeEditor2);
    }

    public Turno crearTurno() {
    // Obtén el nombre del turno desde el JTextField
    String nombre = jTextField1.getText();

    // Obtén la hora de entrada desde el JSpinner
       // Obtén la hora de entrada desde el JSpinner
    Date dateEntrada = (Date) jSpinner1.getValue();
    Calendar calendarEntrada = Calendar.getInstance();
    calendarEntrada.setTime(dateEntrada);
    int horaInicio = calendarEntrada.get(Calendar.HOUR_OF_DAY);
    int minutoInicio = calendarEntrada.get(Calendar.MINUTE);
    Time horaInicioTime = new Time(horaInicio, minutoInicio, 0);

    // Obtén la hora de salida desde el JSpinner
    Date dateSalida = (Date) jSpinner2.getValue();
    Calendar calendarSalida = Calendar.getInstance();
    calendarSalida.setTime(dateSalida);
    int horaFin = calendarSalida.get(Calendar.HOUR_OF_DAY);
    int minutoFin = calendarSalida.get(Calendar.MINUTE);
    Time horaFinTime = new Time(horaFin, minutoFin, 0);

    // Crea el objeto Turno
    Turno turno = new Turno(0,nombre,horaInicioTime,horaFinTime);
 

    return turno;
}
    
    public void cargarDatos(Turno turno) {
    // Configura el JTextField con el nombre del turno
    jTextField1.setText(turno.getNombre());

    // Configura el JSpinner para la hora de entrada
    Time horaInicio = turno.getHoraInicio();
    Calendar calendarInicio = Calendar.getInstance();
    calendarInicio.setTime(horaInicio);
    jSpinner1.setValue(calendarInicio.getTime());

    // Configura el JSpinner para la hora de salida
    Time horaFin = turno.getHoraFin();
    Calendar calendarFin = Calendar.getInstance();
    calendarFin.setTime(horaFin);
    jSpinner2.setValue(calendarFin.getTime());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Hora de inicio");

        jLabel3.setText("Hora de finalizacion");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));

        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      if(act==null){
            con.InsertarTurno(crearTurno());
        }else{
            Turno obj= crearTurno();
            obj.setIdTurno(act.getIdTurno());
 
            con.ModificarTurno(obj);
        }
        frmTurno.Listar();
        this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         act = null;
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
